/**
 * Regenerate the reviewable vocabulary: `docs/vocabulary.png` and
 * `docs/VOCABULARY.md`.
 *
 * A name is a judgement, and the only way to check a judgement about a shape is
 * to look at the shape. So the deliverable is a contact sheet with every name
 * printed on the mark it names, next to a table of the evidence the name was
 * read from — how many icons draw it, at which turns, mirrored or not.
 *
 *   npx tsx scripts/vocabulary-sheet.ts <parts.json>
 *
 * where `<parts.json>` comes from `iconsmith parts <icons> -o`, with no
 * `--min-uses`: the vocabulary now names marks down to three source icons, and
 * a filtered extraction drops six of them out of the doc without saying so. Run
 * it whenever the vocabulary or the extraction changes; a doc nobody
 * regenerates is a doc that quietly stops describing the set.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { nameParts, VOCABULARY } from "../src/parts/vocabulary.js";
import { sheet } from "../src/tools/render.js";
import type { Part } from "../src/types.js";

const DOCS = path.resolve(import.meta.dirname, "../docs");
const COLS = 6;
const TILE = 132;
/** Drawn at true aspect but not true size: the sheet is for reading shapes, and
 *  a 1×2 mark next to a 20×14 one at true scale is a dot next to a drawing. */
const BOX = 17;
const MAX_SCALE = 4;
const STROKE = 2;
const LABEL_SIZE = 2.1;

const tile = (p: Part): string => {
  const s = Math.min(
    BOX / Math.max(p.w, 0.01),
    BOX / Math.max(p.h, 0.01),
    MAX_SCALE
  );
  const dx = 12 - (p.w * s) / 2;
  const dy = 13 - (p.h * s) / 2;
  return `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<g transform="translate(${dx} ${dy}) scale(${s})"><path d="${p.d}" stroke="#000" stroke-width="${STROKE / s}" stroke-linecap="round" stroke-linejoin="round"/></g>
<text x="12" y="3" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="${LABEL_SIZE}" fill="#b00">${p.name}</text>
</svg>`;
};

/** Which quarter-turns the set actually draws, as a readable list. */
const turnsOf = (p: Part): string => {
  const labels = ["0", "90", "180", "270"];
  const drawn = (p.turns ?? []).flatMap((n, i) => (n > 0 ? [labels[i]] : []));
  return drawn.length > 0 ? drawn.join("/") : "—";
};

const flipOf = (p: Part): string => {
  const [plain = 0, mirrored = 0] = p.flips ?? [];
  return mirrored === 0 ? "never" : `${mirrored}/${plain + mirrored}`;
};

const [source] = process.argv.slice(2);
if (!source) {
  process.stderr.write("usage: vocabulary-sheet.ts <parts.json>\n");
  process.exit(1);
}

// The markdown below is written the way the formatter wants it — prose on one
// line, `| --- |` rules — so that regenerating the doc leaves `npm run check`
// green. Rewrapping it here means a fix pass after every run.
const doc = JSON.parse(readFileSync(source, "utf-8")) as { parts: Part[] };
const named = nameParts(doc.parts).filter((p) => p.name);
const notes = new Map(VOCABULARY.map((v) => [v.name, v]));

mkdirSync(DOCS, { recursive: true });
writeFileSync(
  path.join(DOCS, "vocabulary.png"),
  await sheet(named.map(tile), { cols: COLS, size: TILE })
);

const rows = named.map((p) => {
  const v = notes.get(p.name ?? "");
  return `| \`${p.name}\`${v?.sure ? "" : " ⚠"} | ${p.w}×${p.h} | ${p.icons.length} | ${p.instances} | ${turnsOf(p)} | ${flipOf(p)} | ${p.icons.slice(0, 3).join(", ")} |`;
});

const unsure = named.filter((p) => !notes.get(p.name ?? "")?.sure);

writeFileSync(
  path.join(DOCS, "VOCABULARY.md"),
  `# The parts vocabulary

Generated by \`scripts/vocabulary-sheet.ts\` from a \`iconsmith parts\` extraction of ${doc.parts.length} parts, ${named.length} of which a name reaches. The names themselves live in \`src/parts/vocabulary.ts\`, one entry per mark with the canonical drawing it was read off; \`nameParts\` matches them onto an extraction by shape, so they survive a re-run.

![contact sheet](./vocabulary.png)

Read the sheet and the table together — every tile is labelled with the name in the row below. **⚠ marks a name to check before anything depends on it.**

| name | size | icons | instances | turns drawn | mirrored | example icons |
| --- | --- | --- | --- | --- | --- | --- |
${rows.join("\n")}

_turns_ is the quarter-turns the set actually draws the mark at, and _mirrored_ how many of its instances are reflections. Both are measured, and both are the reason a name must not presume a direction: a mark drawn at four turns cannot be called \`bottom-left-corner\` and stay true.

## Names to check (${unsure.length})

${unsure.map((p) => `- **\`${p.name}\`** — ${notes.get(p.name ?? "")?.note}`).join("\n")}
`
);

process.stderr.write(
  `${named.length} named of ${doc.parts.length} parts; ${unsure.length} flagged\n`
);
